server:
  port: 2222

spring:
  application:
    name: EVENT-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: avnadmin
    password: AVNS_GmjvxdOpfKxDlBa0x5R
    url: jdbc:mysql://avnadmin:AVNS_GmjvxdOpfKxDlBa0x5R@mysql-3532b508-aabhivishnu-12b9.d.aivencloud.com:11094/event_rabbiter_event_service?ssl-mode=REQUIRED
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    registry-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0